use crate::Cli;
use clap::{Arg, Command, CommandFactory};
use std::io::Write;

const TEMPLATE: &str = include_str!("../../templates/AGENTS.md.tmpl");

pub fn run() -> Result<(), Box<dyn std::error::Error>> {
    run_to(&mut std::io::stdout())
}

fn run_to<W: Write>(writer: &mut W) -> Result<(), Box<dyn std::error::Error>> {
    let rendered = render();
    writer.write_all(rendered.as_bytes())?;
    Ok(())
}

fn render() -> String {
    let version = env!("CARGO_PKG_VERSION");
    let commands_reference = build_commands_reference();
    TEMPLATE
        .replace("{{ version }}", version)
        .replace("{{ commands_reference }}", &commands_reference)
}

fn build_commands_reference() -> String {
    let cmd = Cli::command();
    let mut output = String::new();
    walk_subcommands(&cmd, "homeos", &mut output);
    output.trim_end().to_string()
}

fn walk_subcommands(cmd: &Command, path: &str, output: &mut String) {
    for sub in cmd.get_subcommands() {
        let sub_name = sub.get_name();
        if sub_name == "help" {
            continue;
        }
        let sub_path = format!("{path} {sub_name}");
        let has_nested_leaves = sub.get_subcommands().any(|s| s.get_name() != "help");
        if has_nested_leaves {
            walk_subcommands(sub, &sub_path, output);
        } else {
            emit_leaf_entry(sub, &sub_path, output);
        }
    }
}

fn emit_leaf_entry(cmd: &Command, path: &str, output: &mut String) {
    output.push_str(&format!("### `{path}`\n\n"));
    if let Some(about) = cmd.get_about() {
        output.push_str(&format!("{about}\n\n"));
    }
    let args: Vec<&Arg> = cmd
        .get_arguments()
        .filter(|a| {
            !a.is_hide_set()
                && !a.is_global_set()
                && a.get_id().as_str() != "help"
                && a.get_id().as_str() != "version"
        })
        .collect();
    if !args.is_empty() {
        for arg in args {
            output.push_str(&format_arg_entry(arg));
            output.push('\n');
        }
        output.push('\n');
    }
}

fn format_arg_entry(arg: &Arg) -> String {
    let identifier = if arg.is_positional() {
        format!("<{}>", arg.get_id().as_str().to_uppercase())
    } else if let Some(long) = arg.get_long() {
        format!("--{long}")
    } else if let Some(short) = arg.get_short() {
        format!("-{short}")
    } else {
        arg.get_id().as_str().to_string()
    };
    let help = arg.get_help().map(|h| h.to_string()).unwrap_or_default();
    if help.is_empty() {
        format!("- `{identifier}`")
    } else {
        format!("- `{identifier}` — {help}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_render_substitutes_version_marker() {
        // Arrange
        let expected_marker = format!("<!-- generated by homeos {} -->", env!("CARGO_PKG_VERSION"));

        // Act
        let rendered = render();

        // Assert
        assert!(
            rendered.starts_with(&expected_marker),
            "expected marker on first line, got: {:?}",
            rendered.lines().next()
        );
        assert!(!rendered.contains("{{ version }}"));
    }

    #[test]
    fn test_render_substitutes_commands_reference_placeholder() {
        // Arrange & Act
        let rendered = render();

        // Assert
        assert!(!rendered.contains("{{ commands_reference }}"));
    }

    #[test]
    fn test_render_commands_reference_includes_top_level_leaves() {
        // Arrange & Act
        let rendered = render();

        // Assert
        assert!(rendered.contains("`homeos init`"));
        assert!(rendered.contains("`homeos cd`"));
        assert!(rendered.contains("`homeos apply`"));
        assert!(rendered.contains("`homeos completion`"));
        assert!(rendered.contains("`homeos agents-md`"));
    }

    #[test]
    fn test_render_commands_reference_includes_nested_leaves() {
        // Arrange & Act
        let rendered = render();

        // Assert
        assert!(rendered.contains("`homeos package list`"));
        assert!(rendered.contains("`homeos package add`"));
        assert!(rendered.contains("`homeos package install`"));
        assert!(rendered.contains("`homeos plugin list`"));
        assert!(rendered.contains("`homeos plugin add`"));
    }

    #[test]
    fn test_build_commands_reference_omits_help_subcommand() {
        // Arrange & Act
        let reference = build_commands_reference();

        // Assert
        assert!(!reference.contains("`homeos help`"));
        assert!(!reference.contains("`homeos package help`"));
    }

    #[test]
    fn test_run_to_writes_rendered_template() {
        // Arrange
        let mut buf: Vec<u8> = Vec::new();
        let expected_marker = format!("<!-- generated by homeos {} -->", env!("CARGO_PKG_VERSION"));

        // Act
        run_to(&mut buf).unwrap();

        // Assert
        let output = String::from_utf8(buf).unwrap();
        assert!(output.starts_with(&expected_marker));
        assert!(output.contains("`homeos init`"));
    }
}
