use crate::Cli;
use clap::{Arg, Command, CommandFactory};
use std::fs;
use std::io::Write;
use std::path::Path;

const TEMPLATE: &str = include_str!("../../templates/AGENTS.md.tmpl");

pub fn run() -> Result<(), Box<dyn std::error::Error>> {
    run_to(&mut std::io::stdout())
}

fn run_to<W: Write>(writer: &mut W) -> Result<(), Box<dyn std::error::Error>> {
    let rendered = render();
    writer.write_all(rendered.as_bytes())?;
    Ok(())
}

/// Render AGENTS.md and write it to `<data_dir>/AGENTS.md`. Also place CLAUDE.md
/// alongside so Claude Code's ancestor scan finds the same content: on Unix
/// CLAUDE.md is a symlink to AGENTS.md; on Windows it is a copy of the rendered
/// content because Windows symlinks require elevated privileges.
pub fn write_files(data_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let rendered = render();
    let agents_md = data_dir.join("AGENTS.md");
    fs::write(&agents_md, &rendered)?;

    let claude_md = data_dir.join("CLAUDE.md");
    if claude_md.symlink_metadata().is_ok() {
        fs::remove_file(&claude_md)?;
    }
    #[cfg(unix)]
    {
        std::os::unix::fs::symlink("AGENTS.md", &claude_md)?;
    }
    #[cfg(windows)]
    {
        fs::write(&claude_md, &rendered)?;
    }

    Ok(())
}

/// Regenerate AGENTS.md and CLAUDE.md if the version embedded in AGENTS.md's
/// first-line marker does not match the current binary's version. Returns
/// `true` when a refresh happened. A one-line notice is written to stderr on
/// refresh so the user sees that the file changed.
pub fn refresh_if_stale(data_dir: &Path) -> Result<bool, Box<dyn std::error::Error>> {
    refresh_if_stale_to(data_dir, &mut std::io::stderr())
}

fn refresh_if_stale_to<W: Write>(
    data_dir: &Path,
    writer: &mut W,
) -> Result<bool, Box<dyn std::error::Error>> {
    let current = env!("CARGO_PKG_VERSION");
    if version_marker_matches(data_dir, current) {
        return Ok(false);
    }
    write_files(data_dir)?;
    writeln!(writer, "homeos: refreshed AGENTS.md to v{current}")?;
    Ok(true)
}

fn version_marker_matches(data_dir: &Path, current: &str) -> bool {
    let path = data_dir.join("AGENTS.md");
    let Ok(content) = fs::read_to_string(&path) else {
        return false;
    };
    let Some(first_line) = content.lines().next() else {
        return false;
    };
    parse_version_marker(first_line) == Some(current)
}

fn parse_version_marker(line: &str) -> Option<&str> {
    line.strip_prefix("<!-- generated by homeos ")?
        .strip_suffix(" -->")
}

fn render() -> String {
    let version = env!("CARGO_PKG_VERSION");
    let commands_reference = build_commands_reference();
    TEMPLATE
        .replace("{{ version }}", version)
        .replace("{{ commands_reference }}", &commands_reference)
}

fn build_commands_reference() -> String {
    let cmd = Cli::command();
    let mut output = String::new();
    walk_subcommands(&cmd, "homeos", &mut output);
    output.trim_end().to_string()
}

fn walk_subcommands(cmd: &Command, path: &str, output: &mut String) {
    for sub in cmd.get_subcommands() {
        let sub_name = sub.get_name();
        if sub_name == "help" {
            continue;
        }
        let sub_path = format!("{path} {sub_name}");
        let has_nested_leaves = sub.get_subcommands().any(|s| s.get_name() != "help");
        if has_nested_leaves {
            walk_subcommands(sub, &sub_path, output);
        } else {
            emit_leaf_entry(sub, &sub_path, output);
        }
    }
}

fn emit_leaf_entry(cmd: &Command, path: &str, output: &mut String) {
    output.push_str(&format!("### `{path}`\n\n"));
    if let Some(about) = cmd.get_about() {
        output.push_str(&format!("{about}\n\n"));
    }
    let args: Vec<&Arg> = cmd
        .get_arguments()
        .filter(|a| {
            !a.is_hide_set()
                && !a.is_global_set()
                && a.get_id().as_str() != "help"
                && a.get_id().as_str() != "version"
        })
        .collect();
    if !args.is_empty() {
        for arg in args {
            output.push_str(&format_arg_entry(arg));
            output.push('\n');
        }
        output.push('\n');
    }
}

fn format_arg_entry(arg: &Arg) -> String {
    let identifier = if arg.is_positional() {
        format!("<{}>", arg.get_id().as_str().to_uppercase())
    } else if let Some(long) = arg.get_long() {
        format!("--{long}")
    } else if let Some(short) = arg.get_short() {
        format!("-{short}")
    } else {
        arg.get_id().as_str().to_string()
    };
    let help = arg.get_help().map(|h| h.to_string()).unwrap_or_default();
    if help.is_empty() {
        format!("- `{identifier}`")
    } else {
        format!("- `{identifier}` — {help}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_render_substitutes_version_marker() {
        // Arrange
        let expected_marker = format!("<!-- generated by homeos {} -->", env!("CARGO_PKG_VERSION"));

        // Act
        let rendered = render();

        // Assert
        assert!(
            rendered.starts_with(&expected_marker),
            "expected marker on first line, got: {:?}",
            rendered.lines().next()
        );
        assert!(!rendered.contains("{{ version }}"));
    }

    #[test]
    fn test_render_substitutes_commands_reference_placeholder() {
        // Arrange & Act
        let rendered = render();

        // Assert
        assert!(!rendered.contains("{{ commands_reference }}"));
    }

    #[test]
    fn test_render_commands_reference_includes_top_level_leaves() {
        // Arrange & Act
        let rendered = render();

        // Assert
        assert!(rendered.contains("`homeos init`"));
        assert!(rendered.contains("`homeos cd`"));
        assert!(rendered.contains("`homeos apply`"));
        assert!(rendered.contains("`homeos completion`"));
        assert!(rendered.contains("`homeos agents-md`"));
    }

    #[test]
    fn test_render_commands_reference_includes_nested_leaves() {
        // Arrange & Act
        let rendered = render();

        // Assert
        assert!(rendered.contains("`homeos package list`"));
        assert!(rendered.contains("`homeos package add`"));
        assert!(rendered.contains("`homeos package install`"));
        assert!(rendered.contains("`homeos plugin list`"));
        assert!(rendered.contains("`homeos plugin add`"));
    }

    #[test]
    fn test_build_commands_reference_omits_help_subcommand() {
        // Arrange & Act
        let reference = build_commands_reference();

        // Assert
        assert!(!reference.contains("`homeos help`"));
        assert!(!reference.contains("`homeos package help`"));
    }

    #[test]
    fn test_run_to_writes_rendered_template() {
        // Arrange
        let mut buf: Vec<u8> = Vec::new();
        let expected_marker = format!("<!-- generated by homeos {} -->", env!("CARGO_PKG_VERSION"));

        // Act
        run_to(&mut buf).unwrap();

        // Assert
        let output = String::from_utf8(buf).unwrap();
        assert!(output.starts_with(&expected_marker));
        assert!(output.contains("`homeos init`"));
    }

    #[test]
    fn test_render_includes_all_top_level_section_headers() {
        // Arrange & Act
        let rendered = render();

        // Assert — each PRD-mandated section header appears exactly as written
        let sections = [
            "## Overview",
            "## Operating principles",
            "## Error JSON schema",
            "## Input safety",
            "## Canonical workflows",
            "## OS-to-plugin mapping reference",
            "## Per-command reference",
            "## Plugin authoring",
            "## Local customizations",
        ];
        for section in sections {
            assert!(
                rendered.contains(section),
                "rendered template missing section header: {section}"
            );
        }
    }

    #[test]
    fn test_render_documents_dry_run_yes_json_flags() {
        // Arrange & Act
        let rendered = render();

        // Assert — Operating principles must mention all three non-interactive flags
        assert!(rendered.contains("--dry-run"));
        assert!(rendered.contains("--yes"));
        assert!(rendered.contains("--json"));
    }

    #[test]
    fn test_render_enumerates_canonical_error_reasons() {
        // Arrange — spot-check a representative subset of the canonical reasons
        let reasons = [
            "package-not-found",
            "plugin-not-found",
            "already-exists",
            "validation-error",
            "circular-dependency",
            "dependency-not-found",
            "dependent-exists",
            "script-failed",
            "script-not-found",
            "script-unmodified",
            "git-clone-failed",
            "not-a-valid-homeos-repo",
            "not-a-valid-homeos-plugin",
            "not-initialized",
            "data-dir-not-empty",
            "data-dir-not-found",
            "directory-not-found",
            "not-found-on-github",
            "network-error",
            "package-installed",
            "internal-error",
        ];

        // Act
        let rendered = render();

        // Assert
        for reason in reasons {
            assert!(
                rendered.contains(reason),
                "rendered template missing canonical reason: {reason}"
            );
        }
    }

    #[test]
    fn test_render_documents_name_and_url_safety_rules() {
        // Arrange & Act
        let rendered = render();

        // Assert — the regex pattern and the allowed URL schemes must appear
        assert!(rendered.contains("^[a-z0-9][a-z0-9._-]*$"));
        for scheme in ["http", "https", "git", "ssh", "git+ssh"] {
            assert!(
                rendered.contains(scheme),
                "rendered template missing allowed URL scheme: {scheme}"
            );
        }
    }

    #[test]
    fn test_render_includes_install_neovim_walkthrough() {
        // Arrange & Act
        let rendered = render();

        // Assert — PRD names "Install Neovim for me" as the headline walk-through
        assert!(rendered.contains("Install Neovim for me"));
        assert!(rendered.contains("homeos --yes --json apply"));
    }

    #[test]
    fn test_render_includes_git_commit_convention() {
        // Arrange & Act
        let rendered = render();

        // Assert — PRD requires documenting the git add/commit pattern after mutation
        assert!(rendered.contains("git add -A"));
        assert!(rendered.contains("git commit"));
    }

    #[test]
    fn test_render_includes_os_to_plugin_mapping_entries() {
        // Arrange & Act
        let rendered = render();

        // Assert — the mapping table must cover the four canonical package managers
        assert!(rendered.contains("dnf"));
        assert!(rendered.contains("apt"));
        assert!(rendered.contains("homebrew"));
        assert!(rendered.contains("winget"));
    }

    #[test]
    fn test_render_instructs_agent_to_read_agents_local_md() {
        // Arrange & Act
        let rendered = render();

        // Assert — Local customizations section must reference AGENTS.local.md by name
        assert!(rendered.contains("AGENTS.local.md"));
    }

    #[test]
    fn test_write_files_creates_agents_md() {
        // Arrange
        let tmp = tempfile::TempDir::new().unwrap();
        let expected_marker = format!("<!-- generated by homeos {} -->", env!("CARGO_PKG_VERSION"));

        // Act
        write_files(tmp.path()).unwrap();

        // Assert
        let agents_md = tmp.path().join("AGENTS.md");
        assert!(agents_md.exists());
        let content = fs::read_to_string(&agents_md).unwrap();
        assert!(content.starts_with(&expected_marker));
    }

    #[test]
    #[cfg(unix)]
    fn test_write_files_creates_claude_md_as_symlink_on_unix() {
        // Arrange
        let tmp = tempfile::TempDir::new().unwrap();

        // Act
        write_files(tmp.path()).unwrap();

        // Assert
        let claude_md = tmp.path().join("CLAUDE.md");
        let metadata = fs::symlink_metadata(&claude_md).unwrap();
        assert!(metadata.file_type().is_symlink());
        let target = fs::read_link(&claude_md).unwrap();
        assert_eq!(target, std::path::PathBuf::from("AGENTS.md"));
    }

    #[test]
    fn test_write_files_overwrites_existing_files() {
        // Arrange
        let tmp = tempfile::TempDir::new().unwrap();
        fs::write(tmp.path().join("AGENTS.md"), "stale content").unwrap();
        fs::write(tmp.path().join("CLAUDE.md"), "stale content").unwrap();
        let expected_marker = format!("<!-- generated by homeos {} -->", env!("CARGO_PKG_VERSION"));

        // Act
        write_files(tmp.path()).unwrap();

        // Assert — AGENTS.md is overwritten with fresh content, CLAUDE.md is replaced
        let agents_content = fs::read_to_string(tmp.path().join("AGENTS.md")).unwrap();
        assert!(agents_content.starts_with(&expected_marker));
        assert!(tmp.path().join("CLAUDE.md").symlink_metadata().is_ok());
    }

    #[test]
    fn test_parse_version_marker_extracts_version() {
        // Arrange & Act
        let result = parse_version_marker("<!-- generated by homeos 1.2.3 -->");

        // Assert
        assert_eq!(result, Some("1.2.3"));
    }

    #[test]
    fn test_parse_version_marker_returns_none_for_unrelated_line() {
        // Arrange & Act
        let result = parse_version_marker("# AGENTS.md");

        // Assert
        assert_eq!(result, None);
    }

    #[test]
    fn test_parse_version_marker_returns_none_for_partial_marker() {
        // Arrange & Act
        let result = parse_version_marker("<!-- generated by homeos 1.2.3");

        // Assert — missing trailing " -->" suffix
        assert_eq!(result, None);
    }

    #[test]
    fn test_refresh_if_stale_regenerates_when_agents_md_missing() {
        // Arrange
        let tmp = tempfile::TempDir::new().unwrap();
        let mut notice: Vec<u8> = Vec::new();

        // Act
        let refreshed = refresh_if_stale_to(tmp.path(), &mut notice).unwrap();

        // Assert
        assert!(refreshed);
        assert!(tmp.path().join("AGENTS.md").exists());
        assert!(tmp.path().join("CLAUDE.md").symlink_metadata().is_ok());
        let notice_text = String::from_utf8(notice).unwrap();
        let expected = format!(
            "homeos: refreshed AGENTS.md to v{}\n",
            env!("CARGO_PKG_VERSION")
        );
        assert_eq!(notice_text, expected);
    }

    #[test]
    fn test_refresh_if_stale_regenerates_when_version_differs() {
        // Arrange
        let tmp = tempfile::TempDir::new().unwrap();
        fs::write(
            tmp.path().join("AGENTS.md"),
            "<!-- generated by homeos 0.0.1 -->\n\nold content\n",
        )
        .unwrap();
        let mut notice: Vec<u8> = Vec::new();

        // Act
        let refreshed = refresh_if_stale_to(tmp.path(), &mut notice).unwrap();

        // Assert — file content is updated to the current version's rendering
        assert!(refreshed);
        let expected_marker = format!("<!-- generated by homeos {} -->", env!("CARGO_PKG_VERSION"));
        let content = fs::read_to_string(tmp.path().join("AGENTS.md")).unwrap();
        assert!(content.starts_with(&expected_marker));
        let notice_text = String::from_utf8(notice).unwrap();
        assert!(notice_text.contains(&format!("v{}", env!("CARGO_PKG_VERSION"))));
    }

    #[test]
    fn test_refresh_if_stale_is_noop_when_version_matches() {
        // Arrange
        let tmp = tempfile::TempDir::new().unwrap();
        write_files(tmp.path()).unwrap();
        let original_content = fs::read_to_string(tmp.path().join("AGENTS.md")).unwrap();
        let original_mtime = fs::metadata(tmp.path().join("AGENTS.md"))
            .unwrap()
            .modified()
            .unwrap();
        let mut notice: Vec<u8> = Vec::new();

        // Act
        let refreshed = refresh_if_stale_to(tmp.path(), &mut notice).unwrap();

        // Assert — no refresh happened, no notice emitted, file untouched
        assert!(!refreshed);
        assert!(notice.is_empty());
        let new_content = fs::read_to_string(tmp.path().join("AGENTS.md")).unwrap();
        assert_eq!(new_content, original_content);
        let new_mtime = fs::metadata(tmp.path().join("AGENTS.md"))
            .unwrap()
            .modified()
            .unwrap();
        assert_eq!(new_mtime, original_mtime);
    }

    #[test]
    fn test_refresh_if_stale_regenerates_when_first_line_unparseable() {
        // Arrange — pre-existing AGENTS.md without the version marker is treated as stale
        let tmp = tempfile::TempDir::new().unwrap();
        fs::write(tmp.path().join("AGENTS.md"), "# Some other content\n").unwrap();
        let mut notice: Vec<u8> = Vec::new();

        // Act
        let refreshed = refresh_if_stale_to(tmp.path(), &mut notice).unwrap();

        // Assert
        assert!(refreshed);
        let expected_marker = format!("<!-- generated by homeos {} -->", env!("CARGO_PKG_VERSION"));
        let content = fs::read_to_string(tmp.path().join("AGENTS.md")).unwrap();
        assert!(content.starts_with(&expected_marker));
    }

    #[test]
    fn test_refresh_if_stale_replaces_claude_md_symlink() {
        // Arrange — a stale AGENTS.md exists but CLAUDE.md does not yet
        let tmp = tempfile::TempDir::new().unwrap();
        fs::write(
            tmp.path().join("AGENTS.md"),
            "<!-- generated by homeos 0.0.1 -->\n",
        )
        .unwrap();
        let mut notice: Vec<u8> = Vec::new();

        // Act
        refresh_if_stale_to(tmp.path(), &mut notice).unwrap();

        // Assert — CLAUDE.md is now in place (symlink on unix, file on windows)
        assert!(tmp.path().join("CLAUDE.md").symlink_metadata().is_ok());
    }
}
