use crate::commands::detect_shell;
use crate::context::Context;
use crate::error::{HomeosError, reasons};
use crate::output::OutputFormat;
use std::io::Write;
use std::path::PathBuf;
use std::process::Command;

/// Resolve and validate the target directory for `homeos cd`.
/// Returns the data directory path if it exists, or an error if not.
pub fn resolve_target(ctx: &Context) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let dir = ctx.data_dir().to_path_buf();
    if !dir.exists() {
        return Err(HomeosError::new(
            reasons::DATA_DIR_NOT_FOUND,
            format!(
                "Data directory not found at {}. Run 'homeos init' first.",
                dir.display()
            ),
        )
        .into());
    }
    Ok(dir)
}

pub fn run(ctx: &Context, print: bool) -> Result<(), Box<dyn std::error::Error>> {
    let dir = resolve_target(ctx)?;
    if print {
        return print_path(&dir, ctx.output_format(), &mut std::io::stdout());
    }
    entry_sequence(&dir, &mut std::io::stderr())?;
    let shell = detect_shell();

    let status = Command::new(&shell).current_dir(&dir).status()?;

    if !status.success() {
        std::process::exit(status.code().unwrap_or(1));
    }
    Ok(())
}

/// Run the pre-shell entry side effects in their canonical order: refresh
/// AGENTS.md first (the local state change — "you are now on vX"), then emit the
/// update-available notice (the outside-world advisory). Reading chronologically,
/// the user sees what just changed locally before what exists upstream, and the
/// actionable advisory lands closest to the prompt. The refresh error is fatal
/// (it propagates); the best-effort update check never blocks `cd`.
fn entry_sequence<W: Write>(
    dir: &std::path::Path,
    writer: &mut W,
) -> Result<(), Box<dyn std::error::Error>> {
    crate::commands::agents_md::refresh_if_stale_to(dir, writer)?;
    let _ = crate::commands::update_check::check_and_notify_to_writer(dir, writer);
    Ok(())
}

fn print_path<W: Write>(
    dir: &std::path::Path,
    format: OutputFormat,
    writer: &mut W,
) -> Result<(), Box<dyn std::error::Error>> {
    match format {
        OutputFormat::Json => {
            let value = serde_json::json!({ "path": dir.display().to_string() });
            writeln!(writer, "{value}")?;
        }
        OutputFormat::Text => {
            writeln!(writer, "{}", dir.display())?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::commands::init;
    use crate::env_test::EnvVarGuard;
    use tempfile::TempDir;

    fn fixture() -> (TempDir, Context) {
        let tmp = TempDir::new().unwrap();
        let ctx = Context::new(Some(tmp.path().join("homeos")));
        (tmp, ctx)
    }

    #[test]
    fn test_resolve_target_returns_data_dir() {
        // Arrange
        let (_tmp, ctx) = fixture();
        init::run(&ctx, None, false).unwrap();

        // Act
        let result = resolve_target(&ctx).unwrap();

        // Assert
        assert_eq!(result, ctx.data_dir());
    }

    #[test]
    fn test_resolve_target_dir_exists() {
        // Arrange
        let (_tmp, ctx) = fixture();
        init::run(&ctx, None, false).unwrap();

        // Act
        let result = resolve_target(&ctx).unwrap();

        // Assert
        assert!(result.exists());
        assert!(result.is_dir());
    }

    #[test]
    fn test_resolve_target_errors_when_not_initialized() {
        // Arrange
        let (_tmp, ctx) = fixture();

        // Act
        let result = resolve_target(&ctx);

        // Assert
        assert!(result.is_err());
        let err = result.unwrap_err().to_string();
        assert!(err.contains("Data directory not found"));
        assert!(err.contains("homeos init"));
    }

    #[test]
    fn test_cd_refreshes_agents_md_when_version_marker_is_stale() {
        // Arrange — init the data dir, then overwrite AGENTS.md with a stale version marker
        // so the refresh path is exercised. (`cd::run` itself spawns a shell, so the test
        // calls into the agents_md refresh helper directly, mirroring what `run` does
        // immediately after `resolve_target`.)
        let (_tmp, ctx) = fixture();
        init::run(&ctx, None, false).unwrap();
        std::fs::write(
            ctx.data_dir().join("AGENTS.md"),
            "<!-- generated by homeos 0.0.1 -->\nstale\n",
        )
        .unwrap();

        // Act
        crate::commands::agents_md::refresh_if_stale_to(
            &resolve_target(&ctx).unwrap(),
            &mut std::io::sink(),
        )
        .unwrap();

        // Assert — the file is regenerated with the current version marker
        let content = std::fs::read_to_string(ctx.data_dir().join("AGENTS.md")).unwrap();
        let expected_marker = format!("<!-- generated by homeos {} -->", env!("CARGO_PKG_VERSION"));
        assert!(content.starts_with(&expected_marker));
    }

    #[test]
    fn test_entry_sequence_refreshes_agents_md_before_update_notice() {
        // Arrange — force BOTH stderr lines to fire: a stale AGENTS.md marker
        // triggers the refresh, and a fresh cache holding a strictly-newer tag
        // triggers the update notice (fresh cache → no network call). Clear the
        // skip env var so the update check actually runs.
        let guard = EnvVarGuard::capture("HOMEOS_SKIP_UPDATE_CHECK");
        guard.unset();
        let (_tmp, ctx) = fixture();
        init::run(&ctx, None, false).unwrap();
        let dir = resolve_target(&ctx).unwrap();
        std::fs::write(
            dir.join("AGENTS.md"),
            "<!-- generated by homeos 0.0.1 -->\nstale\n",
        )
        .unwrap();
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();
        let cache = serde_json::json!({ "last_checked_at": now, "latest_tag": "v99.0.0" });
        std::fs::write(
            crate::commands::update_check::cache_path(&dir),
            cache.to_string(),
        )
        .unwrap();
        let mut output: Vec<u8> = Vec::new();

        // Act
        entry_sequence(&dir, &mut output).unwrap();

        // Assert — the refresh line precedes the update-available line
        let text = String::from_utf8(output).unwrap();
        let refresh_idx = text
            .find("refreshed AGENTS.md")
            .expect("refresh notice should be emitted");
        let update_idx = text
            .find("v99.0.0 available")
            .expect("update notice should be emitted");
        assert!(
            refresh_idx < update_idx,
            "AGENTS.md refresh must precede the update notice, got: {text:?}"
        );
    }

    #[test]
    fn test_print_path_text_emits_single_line() {
        // Arrange
        let dir = std::path::PathBuf::from("/home/user/.local/share/homeos");
        let mut output = Vec::new();

        // Act
        print_path(&dir, OutputFormat::Text, &mut output).unwrap();

        // Assert
        let text = String::from_utf8(output).unwrap();
        assert_eq!(text, "/home/user/.local/share/homeos\n");
    }

    #[test]
    fn test_print_path_json_emits_object_with_path() {
        // Arrange
        let dir = std::path::PathBuf::from("/home/user/.local/share/homeos");
        let mut output = Vec::new();

        // Act
        print_path(&dir, OutputFormat::Json, &mut output).unwrap();

        // Assert
        let text = String::from_utf8(output).unwrap();
        let value: serde_json::Value = serde_json::from_str(&text).unwrap();
        assert_eq!(value["path"], "/home/user/.local/share/homeos");
    }

    #[test]
    fn test_run_print_emits_data_dir_to_writer_without_side_effects() {
        // Arrange — init the data dir, then write a stale AGENTS.md. `--print` must NOT
        // refresh it.
        let (_tmp, ctx) = fixture();
        init::run(&ctx, None, false).unwrap();
        let stale_marker = "<!-- generated by homeos 0.0.1 -->\nstale\n";
        std::fs::write(ctx.data_dir().join("AGENTS.md"), stale_marker).unwrap();
        let dir = resolve_target(&ctx).unwrap();
        let mut output = Vec::new();

        // Act
        print_path(&dir, OutputFormat::Text, &mut output).unwrap();

        // Assert — output is the data dir path, AGENTS.md is unchanged
        let text = String::from_utf8(output).unwrap();
        assert_eq!(
            text.trim_end_matches('\n'),
            ctx.data_dir().display().to_string()
        );
        let after = std::fs::read_to_string(ctx.data_dir().join("AGENTS.md")).unwrap();
        assert_eq!(after, stale_marker);
    }

    #[test]
    fn test_run_print_errors_when_data_dir_missing() {
        // Arrange — no init was run, so the data directory does not exist
        let (_tmp, ctx) = fixture();

        // Act
        let result = run(&ctx, true);

        // Assert
        assert!(result.is_err());
        let err = result.unwrap_err();
        let homeos_err = err
            .downcast_ref::<HomeosError>()
            .expect("expected HomeosError");
        assert_eq!(homeos_err.reason, reasons::DATA_DIR_NOT_FOUND);
    }
}
