use crate::config::{Config, PackageConfig};
use crate::context::Context;

pub fn list(ctx: &Context) -> Result<(), Box<dyn std::error::Error>> {
    let config = Config::load(&ctx.config_path())?;

    for (name, pkg) in &config.packages {
        if pkg.enabled {
            println!("{name}");
        } else {
            println!("{name} (disabled)");
        }
    }

    Ok(())
}

pub fn remove(ctx: &Context, package: &str) -> Result<(), Box<dyn std::error::Error>> {
    let mut config = Config::load(&ctx.config_path())?;

    if !config.packages.contains_key(package) {
        return Err(format!("Package '{package}' not found").into());
    }

    config.packages.remove(package);
    config.save(&ctx.config_path())?;

    println!("Removed package '{package}'");
    Ok(())
}

pub fn add(ctx: &Context, package: &str) -> Result<(), Box<dyn std::error::Error>> {
    let mut config = Config::load(&ctx.config_path())?;

    if config.packages.contains_key(package) {
        return Err(format!("Package '{package}' already exists").into());
    }

    config
        .packages
        .insert(package.to_string(), PackageConfig::default());
    config.save(&ctx.config_path())?;

    let pkg_dir = ctx.packages_dir().join(package);
    std::fs::create_dir_all(&pkg_dir)?;

    for (action, ext) in skeleton_scripts() {
        let filename = format!("{action}.{ext}");
        let content = skeleton_script_content(action, ext, package);
        std::fs::write(pkg_dir.join(&filename), content)?;
    }

    println!("Added package '{package}'");
    Ok(())
}

fn skeleton_scripts() -> Vec<(&'static str, &'static str)> {
    let actions = ["install", "update", "uninstall"];
    let ext = if cfg!(windows) { "ps1" } else { "sh" };
    actions.iter().map(|a| (*a, ext)).collect()
}

fn skeleton_script_content(action: &str, ext: &str, package: &str) -> String {
    let comment = if ext == "ps1" { "#" } else { "#" };
    format!(
        "{comment}!/usr/bin/env {shell}\n\
         {comment} Generated by homeos — fill in the {action} logic for {package}.\n",
        shell = if ext == "ps1" { "pwsh" } else { "sh" },
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn fixture(yaml: &str) -> (TempDir, Context) {
        let tmp = TempDir::new().unwrap();
        let base_dir = tmp.path().to_path_buf();
        let ctx = Context::new(Some(base_dir));

        std::fs::create_dir_all(ctx.config_path().parent().unwrap()).unwrap();
        std::fs::write(ctx.config_path(), yaml).unwrap();

        (tmp, ctx)
    }

    #[test]
    fn test_list_shows_all_packages() {
        // Arrange
        let (_tmp, ctx) = fixture(
            "packages:\n  neovim: {}\n  ripgrep: {}\n  starship: {}\n",
        );

        // Act
        let result = list(&ctx);

        // Assert
        assert!(result.is_ok());
    }

    #[test]
    fn test_list_empty_packages() {
        // Arrange
        let (_tmp, ctx) = fixture("packages: {}\n");

        // Act
        let result = list(&ctx);

        // Assert
        assert!(result.is_ok());
    }

    #[test]
    fn test_list_errors_when_not_initialized() {
        // Arrange
        let tmp = TempDir::new().unwrap();
        let ctx = Context::new(Some(tmp.path().to_path_buf()));

        // Act
        let result = list(&ctx);

        // Assert
        assert!(result.is_err());
    }

    #[test]
    fn test_add_creates_package_dir_and_config_entry() {
        // Arrange
        let (_tmp, ctx) = fixture("packages: {}\n");
        std::fs::create_dir_all(ctx.packages_dir()).unwrap();

        // Act
        let result = add(&ctx, "neovim");

        // Assert
        assert!(result.is_ok());
        let config = Config::load(&ctx.config_path()).unwrap();
        assert!(config.packages.contains_key("neovim"));
        assert!(ctx.packages_dir().join("neovim").is_dir());
    }

    #[test]
    fn test_add_generates_skeleton_scripts() {
        // Arrange
        let (_tmp, ctx) = fixture("packages: {}\n");
        std::fs::create_dir_all(ctx.packages_dir()).unwrap();

        // Act
        add(&ctx, "neovim").unwrap();

        // Assert
        let pkg_dir = ctx.packages_dir().join("neovim");
        let ext = if cfg!(windows) { "ps1" } else { "sh" };
        for action in &["install", "update", "uninstall"] {
            let script = pkg_dir.join(format!("{action}.{ext}"));
            assert!(script.is_file(), "Expected {action}.{ext} to exist");
        }
    }

    #[test]
    fn test_add_skeleton_scripts_contain_comment() {
        // Arrange
        let (_tmp, ctx) = fixture("packages: {}\n");
        std::fs::create_dir_all(ctx.packages_dir()).unwrap();

        // Act
        add(&ctx, "neovim").unwrap();

        // Assert
        let pkg_dir = ctx.packages_dir().join("neovim");
        let ext = if cfg!(windows) { "ps1" } else { "sh" };
        let content = std::fs::read_to_string(pkg_dir.join(format!("install.{ext}"))).unwrap();
        assert!(content.contains("Generated by homeos"));
        assert!(content.contains("install"));
        assert!(content.contains("neovim"));
    }

    #[test]
    fn test_add_errors_when_package_already_exists() {
        // Arrange
        let (_tmp, ctx) = fixture("packages:\n  neovim: {}\n");

        // Act
        let result = add(&ctx, "neovim");

        // Assert
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("already exists"));
    }

    #[test]
    fn test_add_errors_when_not_initialized() {
        // Arrange
        let tmp = TempDir::new().unwrap();
        let ctx = Context::new(Some(tmp.path().to_path_buf()));

        // Act
        let result = add(&ctx, "neovim");

        // Assert
        assert!(result.is_err());
    }

    #[test]
    fn test_add_preserves_existing_packages() {
        // Arrange
        let (_tmp, ctx) = fixture("packages:\n  ripgrep: {}\n");
        std::fs::create_dir_all(ctx.packages_dir()).unwrap();

        // Act
        let result = add(&ctx, "neovim");

        // Assert
        assert!(result.is_ok());
        let config = Config::load(&ctx.config_path()).unwrap();
        assert!(config.packages.contains_key("ripgrep"));
        assert!(config.packages.contains_key("neovim"));
    }

    #[test]
    fn test_list_formats_enabled_and_disabled() {
        // Arrange
        let (_tmp, ctx) = fixture(
            "packages:\n  neovim:\n    enabled: false\n  ripgrep: {}\n",
        );
        let config = Config::load(&ctx.config_path()).unwrap();

        // Act
        let output: Vec<String> = config
            .packages
            .iter()
            .map(|(name, pkg)| {
                if pkg.enabled {
                    name.clone()
                } else {
                    format!("{name} (disabled)")
                }
            })
            .collect();

        // Assert
        assert_eq!(output, vec!["neovim (disabled)", "ripgrep"]);
    }

    #[test]
    fn test_remove_deletes_config_entry() {
        // Arrange
        let (_tmp, ctx) = fixture("packages:\n  neovim: {}\n  ripgrep: {}\n");

        // Act
        let result = remove(&ctx, "neovim");

        // Assert
        assert!(result.is_ok());
        let config = Config::load(&ctx.config_path()).unwrap();
        assert!(!config.packages.contains_key("neovim"));
        assert!(config.packages.contains_key("ripgrep"));
    }

    #[test]
    fn test_remove_errors_when_package_not_found() {
        // Arrange
        let (_tmp, ctx) = fixture("packages:\n  neovim: {}\n");

        // Act
        let result = remove(&ctx, "nonexistent");

        // Assert
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("not found"));
    }

    #[test]
    fn test_remove_errors_when_not_initialized() {
        // Arrange
        let tmp = TempDir::new().unwrap();
        let ctx = Context::new(Some(tmp.path().to_path_buf()));

        // Act
        let result = remove(&ctx, "neovim");

        // Assert
        assert!(result.is_err());
    }

    #[test]
    fn test_remove_last_package_leaves_empty_packages() {
        // Arrange
        let (_tmp, ctx) = fixture("packages:\n  neovim: {}\n");

        // Act
        let result = remove(&ctx, "neovim");

        // Assert
        assert!(result.is_ok());
        let config = Config::load(&ctx.config_path()).unwrap();
        assert!(config.packages.is_empty());
    }
}
