use crate::config::{Config, PackageConfig};
use std::collections::{BTreeMap, HashMap, HashSet, VecDeque};
use std::fmt;
use std::io::{BufRead, Write};
use std::path::Path;

/// The three actions that can be performed on a package.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Action {
    Install,
    Update,
    Uninstall,
}

impl Action {
    /// Past tense verb for plan display (e.g., "installed").
    pub fn past_tense(self) -> &'static str {
        match self {
            Action::Install => "installed",
            Action::Update => "updated",
            Action::Uninstall => "uninstalled",
        }
    }

    /// Present participle for progress messages (e.g., "Installing").
    pub fn gerund(self) -> &'static str {
        match self {
            Action::Install => "Installing",
            Action::Update => "Updating",
            Action::Uninstall => "Uninstalling",
        }
    }

    /// Action name as used in script filenames and aliases (e.g., "install").
    pub fn as_str(self) -> &'static str {
        match self {
            Action::Install => "install",
            Action::Update => "update",
            Action::Uninstall => "uninstall",
        }
    }
}

impl fmt::Display for Action {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// A plan describing which packages will be acted on and which are skipped.
#[derive(Debug, PartialEq)]
pub struct Plan {
    pub action: Action,
    pub enabled: Vec<String>,
    pub disabled: Vec<String>,
    pub already_installed: Vec<String>,
    pub not_installed: Vec<String>,
    /// Packages involved in a circular dependency (skipped).
    pub circular_dependency: Vec<String>,
    /// Packages skipped because a dependency is disabled (directly or transitively).
    /// Maps package name to the most direct unavailable dependency name.
    pub dependency_disabled: BTreeMap<String, String>,
    /// Packages skipped because their action script is still an unmodified skeleton.
    /// Maps package name to the unmodified script filename (e.g., `install.sh`).
    pub script_unmodified: BTreeMap<String, String>,
    /// Plugin name per package (only for packages that use a plugin).
    pub plugins: BTreeMap<String, String>,
    /// Per-package notes shown in the plan (e.g., "depends on B" for reverse deps).
    pub notes: BTreeMap<String, String>,
}

impl Plan {
    /// Build a plan for the given action and package names.
    /// Looks up each package in the config to determine enabled/disabled status.
    /// If `installed` is provided, already-installed packages are classified separately
    /// and will not be executed.
    /// If `packages_dir` is provided, enabled packages whose action script still
    /// contains the `Generated by homeos` skeleton marker are reclassified as skipped
    /// with a `script unmodified: <filename>` reason and excluded from execution.
    pub fn build(
        config: &Config,
        packages: &[String],
        action: Action,
        installed: &[String],
        packages_dir: Option<&Path>,
    ) -> Result<Self, Box<dyn std::error::Error>> {
        let mut enabled = Vec::new();
        let mut disabled = Vec::new();
        let mut already_installed = Vec::new();
        let mut not_installed = Vec::new();

        for name in packages {
            let pkg = config
                .packages
                .get(name)
                .ok_or_else(|| format!("Package '{name}' not found"))?;

            let in_state = installed.contains(name);

            match action {
                Action::Install => {
                    if !pkg.enabled {
                        disabled.push(name.clone());
                    } else if in_state {
                        already_installed.push(name.clone());
                    } else {
                        enabled.push(name.clone());
                    }
                }
                Action::Update => {
                    if !pkg.enabled {
                        disabled.push(name.clone());
                    } else if in_state {
                        enabled.push(name.clone());
                    } else {
                        not_installed.push(name.clone());
                    }
                }
                Action::Uninstall => {
                    if in_state {
                        enabled.push(name.clone());
                    } else {
                        not_installed.push(name.clone());
                    }
                }
            }
        }

        // For Install, propagate disabled status: any enabled package whose dependency
        // chain includes a disabled package is reclassified as skipped with
        // "dependency disabled: <name>" annotation, where <name> is the most direct
        // unavailable dependency.
        let mut dependency_disabled: BTreeMap<String, String> = BTreeMap::new();
        if action == Action::Install && !enabled.is_empty() {
            let unavailable = compute_unavailable_packages(config);
            let mut still_enabled: Vec<String> = Vec::new();
            for name in std::mem::take(&mut enabled) {
                let pkg = &config.packages[&name];
                let mut unavailable_direct_deps: Vec<&String> = pkg
                    .depends_on
                    .iter()
                    .filter(|d| unavailable.contains(d.as_str()))
                    .collect();
                if unavailable_direct_deps.is_empty() {
                    still_enabled.push(name);
                } else {
                    unavailable_direct_deps.sort();
                    dependency_disabled.insert(name, unavailable_direct_deps[0].clone());
                }
            }
            enabled = still_enabled;
        }

        // For any action, if the script that would execute is still the unmodified
        // skeleton (contains the `Generated by homeos` marker), reclassify the package
        // as skipped so it is NOT executed. This prevents the silent failure where an
        // empty install script would mark a package as installed in state.yml.
        let mut script_unmodified: BTreeMap<String, String> = BTreeMap::new();
        if let Some(dir) = packages_dir {
            let mut still_enabled: Vec<String> = Vec::new();
            for name in std::mem::take(&mut enabled) {
                let pkg_config = &config.packages[&name];
                let script_name = resolve_script_name(pkg_config, action);
                let script_path = dir.join(&name).join(&script_name);
                let is_unmodified = std::fs::read_to_string(&script_path)
                    .map(|content| content.contains("Generated by homeos"))
                    .unwrap_or(false);
                if is_unmodified {
                    script_unmodified.insert(name, script_name);
                } else {
                    still_enabled.push(name);
                }
            }
            enabled = still_enabled;
        }

        let mut plugins: BTreeMap<String, String> = BTreeMap::new();
        for name in enabled
            .iter()
            .chain(disabled.iter())
            .chain(already_installed.iter())
            .chain(not_installed.iter())
            .chain(dependency_disabled.keys())
            .chain(script_unmodified.keys())
        {
            if let Some(pkg) = config.packages.get(name)
                && let Some(ref plugin_name) = pkg.plugin
            {
                plugins.insert(name.clone(), plugin_name.clone());
            }
        }

        Ok(Plan {
            action,
            enabled,
            disabled,
            already_installed,
            not_installed,
            circular_dependency: Vec::new(),
            dependency_disabled,
            script_unmodified,
            plugins,
            notes: BTreeMap::new(),
        })
    }

    /// Format the plan as a human-readable string for display.
    pub fn display(&self) -> String {
        let enabled_part = self.display_enabled();
        let skipped_part = self.display_skipped();
        match (enabled_part.is_empty(), skipped_part.is_empty()) {
            (true, true) => String::new(),
            (false, true) => enabled_part,
            (true, false) => skipped_part,
            (false, false) => format!("{enabled_part}\n{skipped_part}"),
        }
    }

    /// Render only the "will be {action}" section. Returns an empty string when no
    /// enabled packages. Used by `apply` to keep enabled sections grouped before the
    /// consolidated skipped section.
    pub fn display_enabled(&self) -> String {
        if self.enabled.is_empty() {
            return String::new();
        }
        let verb = self.action.past_tense();
        let mut lines = Vec::new();
        lines.push(format!("The following packages will be {verb}:"));
        for name in &self.enabled {
            let mut annotations = Vec::new();
            if let Some(note) = self.notes.get(name) {
                annotations.push(note.clone());
            }
            if let Some(plugin_name) = self.plugins.get(name) {
                annotations.push(format!("plugin: {plugin_name}"));
            }
            if annotations.is_empty() {
                lines.push(format!("  {name}"));
            } else {
                let annotation_str = annotations.join(", ");
                lines.push(format!("  {name} ({annotation_str})"));
            }
        }
        lines.join("\n")
    }

    /// Render only the "will be skipped" section (header + entries). Returns an empty
    /// string when nothing is skipped.
    pub fn display_skipped(&self) -> String {
        let mut skipped: Vec<String> = Vec::new();
        for name in &self.disabled {
            let plugin_suffix = self
                .plugins
                .get(name)
                .map(|p| format!(", plugin: {p}"))
                .unwrap_or_default();
            skipped.push(format!("  {name} (disabled{plugin_suffix})"));
        }
        for name in &self.already_installed {
            let plugin_suffix = self
                .plugins
                .get(name)
                .map(|p| format!(", plugin: {p}"))
                .unwrap_or_default();
            skipped.push(format!("  {name} (already installed{plugin_suffix})"));
        }
        for name in &self.not_installed {
            let plugin_suffix = self
                .plugins
                .get(name)
                .map(|p| format!(", plugin: {p}"))
                .unwrap_or_default();
            skipped.push(format!("  {name} (not installed{plugin_suffix})"));
        }
        for name in &self.circular_dependency {
            let plugin_suffix = self
                .plugins
                .get(name)
                .map(|p| format!(", plugin: {p}"))
                .unwrap_or_default();
            skipped.push(format!("  {name} (circular dependency{plugin_suffix})"));
        }
        for (name, blamed) in &self.dependency_disabled {
            let plugin_suffix = self
                .plugins
                .get(name)
                .map(|p| format!(", plugin: {p}"))
                .unwrap_or_default();
            skipped.push(format!(
                "  {name} (dependency disabled: {blamed}{plugin_suffix})"
            ));
        }
        for (name, script_name) in &self.script_unmodified {
            let plugin_suffix = self
                .plugins
                .get(name)
                .map(|p| format!(", plugin: {p}"))
                .unwrap_or_default();
            skipped.push(format!(
                "  {name} (script unmodified: {script_name}{plugin_suffix})"
            ));
        }
        if skipped.is_empty() {
            String::new()
        } else {
            let mut lines = vec!["The following packages will be skipped:".to_string()];
            lines.extend(skipped);
            lines.join("\n")
        }
    }

    /// Returns true if there are no enabled packages to act on.
    pub fn is_empty(&self) -> bool {
        self.enabled.is_empty()
    }
}

/// Compute the set of packages that are unavailable for install, i.e. disabled
/// directly OR transitively reachable from a disabled package via the reverse
/// dependency graph. Used by `Plan::build` to propagate disabled status to dependents.
fn compute_unavailable_packages(config: &Config) -> HashSet<String> {
    let mut reverse_graph: HashMap<&str, Vec<&str>> = HashMap::new();
    for (name, pkg) in &config.packages {
        for dep in &pkg.depends_on {
            reverse_graph
                .entry(dep.as_str())
                .or_default()
                .push(name.as_str());
        }
    }

    let mut unavailable: HashSet<String> = config
        .packages
        .iter()
        .filter(|(_, pkg)| !pkg.enabled)
        .map(|(name, _)| name.clone())
        .collect();

    let mut queue: VecDeque<String> = unavailable.iter().cloned().collect();
    while let Some(name) = queue.pop_front() {
        if let Some(dependents) = reverse_graph.get(name.as_str()) {
            for &dependent in dependents {
                if unavailable.insert(dependent.to_string()) {
                    queue.push_back(dependent.to_string());
                }
            }
        }
    }

    unavailable
}

/// Resolve the script filename for a given action, considering aliases.
fn resolve_script_name(pkg_config: &PackageConfig, action: Action) -> String {
    let action_str = action.as_str();
    let resolved_action = pkg_config
        .script_aliases
        .get(action_str)
        .map(|s| s.as_str())
        .unwrap_or(action_str);
    let ext = crate::commands::package::script_extension();
    format!("{resolved_action}.{ext}")
}

/// Prompt the user for confirmation, reading from the provided reader.
/// Returns true only if the user enters "y" or "Y".
pub fn prompt_confirm<R: BufRead, W: Write>(reader: &mut R, writer: &mut W) -> bool {
    write!(writer, "Proceed? [y/N] ").ok();
    writer.flush().ok();

    let mut input = String::new();
    if reader.read_line(&mut input).is_err() {
        return false;
    }

    matches!(input.trim(), "y" | "Y")
}

/// Show the plan and prompt for confirmation. Returns true if the user confirms.
pub fn confirm_plan<R: BufRead, W: Write>(plan: &Plan, reader: &mut R, writer: &mut W) -> bool {
    let display = plan.display();
    writeln!(writer, "{display}").ok();
    writeln!(writer).ok();
    prompt_confirm(reader, writer)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::PackageConfig;
    use std::io::Cursor;

    fn fixture_config(packages: Vec<(&str, bool)>) -> Config {
        let mut map = BTreeMap::new();
        for (name, enabled) in packages {
            map.insert(
                name.to_string(),
                PackageConfig {
                    enabled,
                    ..Default::default()
                },
            );
        }
        Config {
            packages: map,
            ..Default::default()
        }
    }

    #[test]
    fn test_build_plan_separates_enabled_and_disabled() {
        // Arrange
        let config = fixture_config(vec![("neovim", true), ("docker", false), ("zed", true)]);
        let packages: Vec<String> = vec!["neovim", "docker", "zed"]
            .into_iter()
            .map(String::from)
            .collect();

        // Act
        let sut = Plan::build(&config, &packages, Action::Install, &[], None).unwrap();

        // Assert
        assert_eq!(sut.enabled, vec!["neovim", "zed"]);
        assert_eq!(sut.disabled, vec!["docker"]);
        assert_eq!(sut.action, Action::Install);
    }

    #[test]
    fn test_build_plan_all_enabled() {
        // Arrange
        let config = fixture_config(vec![("neovim", true), ("ripgrep", true)]);
        let packages: Vec<String> = vec!["neovim", "ripgrep"]
            .into_iter()
            .map(String::from)
            .collect();

        // Act
        let sut = Plan::build(&config, &packages, Action::Install, &[], None).unwrap();

        // Assert
        assert_eq!(sut.enabled, vec!["neovim", "ripgrep"]);
        assert!(sut.disabled.is_empty());
    }

    #[test]
    fn test_build_plan_all_disabled() {
        // Arrange
        let config = fixture_config(vec![("neovim", false), ("docker", false)]);
        let packages: Vec<String> = vec!["neovim", "docker"]
            .into_iter()
            .map(String::from)
            .collect();

        // Act
        let sut = Plan::build(&config, &packages, Action::Install, &[], None).unwrap();

        // Assert
        assert!(sut.enabled.is_empty());
        assert_eq!(sut.disabled, vec!["neovim", "docker"]);
        assert!(sut.is_empty());
    }

    #[test]
    fn test_build_plan_errors_on_unknown_package() {
        // Arrange
        let config = fixture_config(vec![("neovim", true)]);
        let packages: Vec<String> = vec!["nonexistent"].into_iter().map(String::from).collect();

        // Act
        let result = Plan::build(&config, &packages, Action::Install, &[], None);

        // Assert
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("not found"));
    }

    #[test]
    fn test_display_shows_enabled_and_disabled() {
        // Arrange
        let plan = Plan {
            action: Action::Install,
            enabled: vec!["neovim".to_string(), "zed".to_string()],
            disabled: vec!["docker".to_string()],
            already_installed: vec![],
            not_installed: vec![],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::new(),
            notes: BTreeMap::new(),
        };

        // Act
        let sut = plan.display();

        // Assert
        let expected = "\
The following packages will be installed:
  neovim
  zed
The following packages will be skipped:
  docker (disabled)";
        assert_eq!(sut, expected);
    }

    #[test]
    fn test_display_only_disabled() {
        // Arrange
        let plan = Plan {
            action: Action::Install,
            enabled: vec![],
            disabled: vec!["docker".to_string()],
            already_installed: vec![],
            not_installed: vec![],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::new(),
            notes: BTreeMap::new(),
        };

        // Act
        let sut = plan.display();

        // Assert
        assert_eq!(
            sut,
            "The following packages will be skipped:\n  docker (disabled)"
        );
    }

    #[test]
    fn test_display_update_verb() {
        // Arrange
        let plan = Plan {
            action: Action::Update,
            enabled: vec!["neovim".to_string()],
            disabled: vec![],
            already_installed: vec![],
            not_installed: vec![],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::new(),
            notes: BTreeMap::new(),
        };

        // Act
        let sut = plan.display();

        // Assert
        assert!(sut.contains("will be updated"));
    }

    #[test]
    fn test_display_uninstall_verb() {
        // Arrange
        let plan = Plan {
            action: Action::Uninstall,
            enabled: vec!["neovim".to_string()],
            disabled: vec![],
            already_installed: vec![],
            not_installed: vec![],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::new(),
            notes: BTreeMap::new(),
        };

        // Act
        let sut = plan.display();

        // Assert
        assert!(sut.contains("will be uninstalled"));
    }

    #[test]
    fn test_prompt_confirm_accepts_y() {
        // Arrange
        let mut input = Cursor::new(b"y\n".to_vec());
        let mut output = Vec::new();

        // Act
        let sut = prompt_confirm(&mut input, &mut output);

        // Assert
        assert!(sut);
    }

    #[test]
    fn test_prompt_confirm_accepts_uppercase_y() {
        // Arrange
        let mut input = Cursor::new(b"Y\n".to_vec());
        let mut output = Vec::new();

        // Act
        let sut = prompt_confirm(&mut input, &mut output);

        // Assert
        assert!(sut);
    }

    #[test]
    fn test_prompt_confirm_rejects_n() {
        // Arrange
        let mut input = Cursor::new(b"n\n".to_vec());
        let mut output = Vec::new();

        // Act
        let sut = prompt_confirm(&mut input, &mut output);

        // Assert
        assert!(!sut);
    }

    #[test]
    fn test_prompt_confirm_rejects_empty() {
        // Arrange
        let mut input = Cursor::new(b"\n".to_vec());
        let mut output = Vec::new();

        // Act
        let sut = prompt_confirm(&mut input, &mut output);

        // Assert
        assert!(!sut);
    }

    #[test]
    fn test_prompt_confirm_writes_prompt_text() {
        // Arrange
        let mut input = Cursor::new(b"n\n".to_vec());
        let mut output = Vec::new();

        // Act
        prompt_confirm(&mut input, &mut output);

        // Assert
        let written = String::from_utf8(output).unwrap();
        assert!(written.contains("Proceed? [y/N]"));
    }

    #[test]
    fn test_confirm_plan_shows_plan_and_prompts() {
        // Arrange
        let plan = Plan {
            action: Action::Install,
            enabled: vec!["neovim".to_string()],
            disabled: vec!["docker".to_string()],
            already_installed: vec![],
            not_installed: vec![],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::new(),
            notes: BTreeMap::new(),
        };
        let mut input = Cursor::new(b"y\n".to_vec());
        let mut output = Vec::new();

        // Act
        let sut = confirm_plan(&plan, &mut input, &mut output);

        // Assert
        assert!(sut);
        let written = String::from_utf8(output).unwrap();
        assert!(written.contains("neovim"));
        assert!(written.contains("docker (disabled)"));
        assert!(written.contains("will be skipped"));
        assert!(written.contains("Proceed? [y/N]"));
    }

    #[test]
    fn test_is_empty_when_no_enabled_packages() {
        // Arrange
        let plan = Plan {
            action: Action::Install,
            enabled: vec![],
            disabled: vec!["docker".to_string()],
            already_installed: vec![],
            not_installed: vec![],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::new(),
            notes: BTreeMap::new(),
        };

        // Act & Assert
        assert!(plan.is_empty());
    }

    #[test]
    fn test_is_not_empty_when_has_enabled_packages() {
        // Arrange
        let plan = Plan {
            action: Action::Install,
            enabled: vec!["neovim".to_string()],
            disabled: vec![],
            already_installed: vec![],
            not_installed: vec![],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::new(),
            notes: BTreeMap::new(),
        };

        // Act & Assert
        assert!(!plan.is_empty());
    }

    #[test]
    fn test_build_plan_classifies_already_installed() {
        // Arrange
        let config = fixture_config(vec![("neovim", true), ("zed", true), ("docker", false)]);
        let packages: Vec<String> = vec!["neovim", "zed", "docker"]
            .into_iter()
            .map(String::from)
            .collect();
        let installed = vec!["neovim".to_string()];

        // Act
        let sut = Plan::build(&config, &packages, Action::Install, &installed, None).unwrap();

        // Assert
        assert_eq!(sut.enabled, vec!["zed"]);
        assert_eq!(sut.disabled, vec!["docker"]);
        assert_eq!(sut.already_installed, vec!["neovim"]);
    }

    #[test]
    fn test_build_plan_all_already_installed() {
        // Arrange
        let config = fixture_config(vec![("neovim", true), ("zed", true)]);
        let packages: Vec<String> = vec!["neovim", "zed"]
            .into_iter()
            .map(String::from)
            .collect();
        let installed = vec!["neovim".to_string(), "zed".to_string()];

        // Act
        let sut = Plan::build(&config, &packages, Action::Install, &installed, None).unwrap();

        // Assert
        assert!(sut.enabled.is_empty());
        assert!(sut.is_empty());
        assert_eq!(sut.already_installed, vec!["neovim", "zed"]);
    }

    #[test]
    fn test_display_shows_already_installed() {
        // Arrange
        let plan = Plan {
            action: Action::Install,
            enabled: vec!["zed".to_string()],
            disabled: vec![],
            already_installed: vec!["neovim".to_string()],
            not_installed: vec![],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::new(),
            notes: BTreeMap::new(),
        };

        // Act
        let sut = plan.display();

        // Assert
        assert!(sut.contains("neovim (already installed)"));
        assert!(sut.contains("will be skipped"));
        assert!(sut.contains("will be installed"));
        assert!(sut.contains("zed"));
    }

    #[test]
    fn test_build_plan_uninstall_ignores_disabled_status() {
        // Arrange
        let config = fixture_config(vec![("neovim", false), ("zed", true)]);
        let packages: Vec<String> = vec!["neovim", "zed"]
            .into_iter()
            .map(String::from)
            .collect();
        let installed = vec!["neovim".to_string(), "zed".to_string()];

        // Act
        let sut = Plan::build(&config, &packages, Action::Uninstall, &installed, None).unwrap();

        // Assert
        assert_eq!(sut.enabled, vec!["neovim", "zed"]);
        assert!(sut.disabled.is_empty());
    }

    #[test]
    fn test_build_plan_install_still_skips_disabled() {
        // Arrange
        let config = fixture_config(vec![("neovim", false), ("zed", true)]);
        let packages: Vec<String> = vec!["neovim", "zed"]
            .into_iter()
            .map(String::from)
            .collect();

        // Act
        let sut = Plan::build(&config, &packages, Action::Install, &[], None).unwrap();

        // Assert
        assert_eq!(sut.enabled, vec!["zed"]);
        assert_eq!(sut.disabled, vec!["neovim"]);
    }

    #[test]
    fn test_build_plan_has_empty_not_installed_by_default() {
        // Arrange
        let config = fixture_config(vec![("neovim", true), ("zed", true)]);
        let packages: Vec<String> = vec!["neovim", "zed"]
            .into_iter()
            .map(String::from)
            .collect();

        // Act
        let sut = Plan::build(&config, &packages, Action::Install, &[], None).unwrap();

        // Assert
        assert!(sut.not_installed.is_empty());
    }

    #[test]
    fn test_build_plan_already_installed_only_applies_to_install_action() {
        // Arrange
        let config = fixture_config(vec![("neovim", true)]);
        let packages: Vec<String> = vec!["neovim"].into_iter().map(String::from).collect();
        let installed = vec!["neovim".to_string()];

        // Act
        let sut = Plan::build(&config, &packages, Action::Update, &installed, None).unwrap();

        // Assert — for update, being in state means execute (enabled), not already_installed
        assert_eq!(sut.enabled, vec!["neovim"]);
        assert!(sut.already_installed.is_empty());
    }

    #[test]
    fn test_display_shows_not_installed() {
        // Arrange
        let plan = Plan {
            action: Action::Update,
            enabled: vec!["zed".to_string()],
            disabled: vec![],
            already_installed: vec![],
            not_installed: vec!["neovim".to_string()],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::new(),
            notes: BTreeMap::new(),
        };

        // Act
        let sut = plan.display();

        // Assert
        assert!(sut.contains("neovim (not installed)"));
        assert!(sut.contains("will be skipped"));
        assert!(sut.contains("will be updated"));
        assert!(sut.contains("zed"));
    }

    #[test]
    fn test_display_groups_mixed_skip_reasons_under_single_header() {
        // Arrange
        let plan = Plan {
            action: Action::Install,
            enabled: vec!["zed".to_string()],
            disabled: vec!["docker".to_string()],
            already_installed: vec!["neovim".to_string()],
            not_installed: vec![],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::new(),
            notes: BTreeMap::new(),
        };

        // Act
        let sut = plan.display();

        // Assert
        let expected = "\
The following packages will be installed:
  zed
The following packages will be skipped:
  docker (disabled)
  neovim (already installed)";
        assert_eq!(sut, expected);
    }

    #[test]
    fn test_display_no_skip_header_when_no_skipped_packages() {
        // Arrange
        let plan = Plan {
            action: Action::Install,
            enabled: vec!["neovim".to_string()],
            disabled: vec![],
            already_installed: vec![],
            not_installed: vec![],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::new(),
            notes: BTreeMap::new(),
        };

        // Act
        let sut = plan.display();

        // Assert
        assert!(!sut.contains("will be skipped"));
        assert_eq!(sut, "The following packages will be installed:\n  neovim");
    }

    #[test]
    fn test_display_all_skip_reasons_combined() {
        // Arrange
        let plan = Plan {
            action: Action::Install,
            enabled: vec![],
            disabled: vec!["docker".to_string()],
            already_installed: vec!["neovim".to_string()],
            not_installed: vec!["ripgrep".to_string()],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::new(),
            notes: BTreeMap::new(),
        };

        // Act
        let sut = plan.display();

        // Assert
        let expected = "\
The following packages will be skipped:
  docker (disabled)
  neovim (already installed)
  ripgrep (not installed)";
        assert_eq!(sut, expected);
    }

    // --- Behavior matrix tests ---

    #[test]
    fn test_behavior_matrix_install_enabled_not_in_state_executes() {
        // Arrange
        let config = fixture_config(vec![("neovim", true)]);
        let packages: Vec<String> = vec!["neovim"].into_iter().map(String::from).collect();

        // Act
        let sut = Plan::build(&config, &packages, Action::Install, &[], None).unwrap();

        // Assert
        assert_eq!(sut.enabled, vec!["neovim"]);
    }

    #[test]
    fn test_behavior_matrix_install_enabled_in_state_skips_already_installed() {
        // Arrange
        let config = fixture_config(vec![("neovim", true)]);
        let packages: Vec<String> = vec!["neovim"].into_iter().map(String::from).collect();
        let installed = vec!["neovim".to_string()];

        // Act
        let sut = Plan::build(&config, &packages, Action::Install, &installed, None).unwrap();

        // Assert
        assert!(sut.enabled.is_empty());
        assert_eq!(sut.already_installed, vec!["neovim"]);
    }

    #[test]
    fn test_behavior_matrix_install_disabled_not_in_state_skips_disabled() {
        // Arrange
        let config = fixture_config(vec![("neovim", false)]);
        let packages: Vec<String> = vec!["neovim"].into_iter().map(String::from).collect();

        // Act
        let sut = Plan::build(&config, &packages, Action::Install, &[], None).unwrap();

        // Assert
        assert!(sut.enabled.is_empty());
        assert_eq!(sut.disabled, vec!["neovim"]);
    }

    #[test]
    fn test_behavior_matrix_install_disabled_in_state_skips_disabled() {
        // Arrange
        let config = fixture_config(vec![("neovim", false)]);
        let packages: Vec<String> = vec!["neovim"].into_iter().map(String::from).collect();
        let installed = vec!["neovim".to_string()];

        // Act
        let sut = Plan::build(&config, &packages, Action::Install, &installed, None).unwrap();

        // Assert
        assert!(sut.enabled.is_empty());
        assert_eq!(sut.disabled, vec!["neovim"]);
    }

    #[test]
    fn test_behavior_matrix_update_enabled_not_in_state_skips_not_installed() {
        // Arrange
        let config = fixture_config(vec![("neovim", true)]);
        let packages: Vec<String> = vec!["neovim"].into_iter().map(String::from).collect();

        // Act
        let sut = Plan::build(&config, &packages, Action::Update, &[], None).unwrap();

        // Assert
        assert!(sut.enabled.is_empty());
        assert_eq!(sut.not_installed, vec!["neovim"]);
    }

    #[test]
    fn test_behavior_matrix_update_enabled_in_state_executes() {
        // Arrange
        let config = fixture_config(vec![("neovim", true)]);
        let packages: Vec<String> = vec!["neovim"].into_iter().map(String::from).collect();
        let installed = vec!["neovim".to_string()];

        // Act
        let sut = Plan::build(&config, &packages, Action::Update, &installed, None).unwrap();

        // Assert
        assert_eq!(sut.enabled, vec!["neovim"]);
    }

    #[test]
    fn test_behavior_matrix_update_disabled_not_in_state_skips_disabled() {
        // Arrange
        let config = fixture_config(vec![("neovim", false)]);
        let packages: Vec<String> = vec!["neovim"].into_iter().map(String::from).collect();

        // Act
        let sut = Plan::build(&config, &packages, Action::Update, &[], None).unwrap();

        // Assert
        assert!(sut.enabled.is_empty());
        assert_eq!(sut.disabled, vec!["neovim"]);
    }

    #[test]
    fn test_behavior_matrix_update_disabled_in_state_skips_disabled() {
        // Arrange
        let config = fixture_config(vec![("neovim", false)]);
        let packages: Vec<String> = vec!["neovim"].into_iter().map(String::from).collect();
        let installed = vec!["neovim".to_string()];

        // Act
        let sut = Plan::build(&config, &packages, Action::Update, &installed, None).unwrap();

        // Assert
        assert!(sut.enabled.is_empty());
        assert_eq!(sut.disabled, vec!["neovim"]);
    }

    #[test]
    fn test_behavior_matrix_uninstall_enabled_not_in_state_skips_not_installed() {
        // Arrange
        let config = fixture_config(vec![("neovim", true)]);
        let packages: Vec<String> = vec!["neovim"].into_iter().map(String::from).collect();

        // Act
        let sut = Plan::build(&config, &packages, Action::Uninstall, &[], None).unwrap();

        // Assert
        assert!(sut.enabled.is_empty());
        assert_eq!(sut.not_installed, vec!["neovim"]);
    }

    #[test]
    fn test_behavior_matrix_uninstall_enabled_in_state_executes() {
        // Arrange
        let config = fixture_config(vec![("neovim", true)]);
        let packages: Vec<String> = vec!["neovim"].into_iter().map(String::from).collect();
        let installed = vec!["neovim".to_string()];

        // Act
        let sut = Plan::build(&config, &packages, Action::Uninstall, &installed, None).unwrap();

        // Assert
        assert_eq!(sut.enabled, vec!["neovim"]);
    }

    #[test]
    fn test_behavior_matrix_uninstall_disabled_not_in_state_skips_not_installed() {
        // Arrange
        let config = fixture_config(vec![("neovim", false)]);
        let packages: Vec<String> = vec!["neovim"].into_iter().map(String::from).collect();

        // Act
        let sut = Plan::build(&config, &packages, Action::Uninstall, &[], None).unwrap();

        // Assert
        assert!(sut.enabled.is_empty());
        assert_eq!(sut.not_installed, vec!["neovim"]);
        assert!(sut.disabled.is_empty());
    }

    #[test]
    fn test_behavior_matrix_uninstall_disabled_in_state_executes() {
        // Arrange
        let config = fixture_config(vec![("neovim", false)]);
        let packages: Vec<String> = vec!["neovim"].into_iter().map(String::from).collect();
        let installed = vec!["neovim".to_string()];

        // Act
        let sut = Plan::build(&config, &packages, Action::Uninstall, &installed, None).unwrap();

        // Assert
        assert_eq!(sut.enabled, vec!["neovim"]);
        assert!(sut.disabled.is_empty());
    }

    // --- Action enum tests ---

    #[test]
    fn test_action_as_str() {
        // Arrange
        let actions = [Action::Install, Action::Update, Action::Uninstall];

        // Act
        let names: Vec<&str> = actions.iter().map(|a| a.as_str()).collect();

        // Assert
        assert_eq!(names, vec!["install", "update", "uninstall"]);
    }

    #[test]
    fn test_action_past_tense() {
        // Arrange
        let actions = [Action::Install, Action::Update, Action::Uninstall];

        // Act
        let verbs: Vec<&str> = actions.iter().map(|a| a.past_tense()).collect();

        // Assert
        assert_eq!(verbs, vec!["installed", "updated", "uninstalled"]);
    }

    #[test]
    fn test_action_gerund() {
        // Arrange
        let actions = [Action::Install, Action::Update, Action::Uninstall];

        // Act
        let gerunds: Vec<&str> = actions.iter().map(|a| a.gerund()).collect();

        // Assert
        assert_eq!(gerunds, vec!["Installing", "Updating", "Uninstalling"]);
    }

    #[test]
    fn test_action_display() {
        // Arrange / Act / Assert
        assert_eq!(format!("{}", Action::Install), "install");
        assert_eq!(format!("{}", Action::Update), "update");
        assert_eq!(format!("{}", Action::Uninstall), "uninstall");
    }

    #[test]
    fn test_action_equality() {
        // Arrange / Act / Assert
        assert_eq!(Action::Install, Action::Install);
        assert_ne!(Action::Install, Action::Update);
        assert_ne!(Action::Update, Action::Uninstall);
    }

    // --- Unmodified skeleton script skip tests ---

    #[test]
    fn test_build_classifies_unmodified_skeleton_as_skipped() {
        // Arrange
        let tmp = tempfile::TempDir::new().unwrap();
        let packages_dir = tmp.path().join("packages");
        let pkg_dir = packages_dir.join("neovim");
        std::fs::create_dir_all(&pkg_dir).unwrap();
        let ext = crate::commands::package::script_extension();
        let script_name = format!("install.{ext}");
        std::fs::write(
            pkg_dir.join(&script_name),
            "# Generated by homeos — fill in the install logic for neovim.\n",
        )
        .unwrap();

        let config = fixture_config(vec![("neovim", true)]);

        // Act
        let sut = Plan::build(
            &config,
            &["neovim".to_string()],
            Action::Install,
            &[],
            Some(&packages_dir),
        )
        .unwrap();

        // Assert — neovim moves out of enabled and into script_unmodified
        assert!(sut.enabled.is_empty());
        assert_eq!(sut.script_unmodified.get("neovim"), Some(&script_name));
    }

    #[test]
    fn test_build_ignores_modified_scripts() {
        // Arrange
        let tmp = tempfile::TempDir::new().unwrap();
        let packages_dir = tmp.path().join("packages");
        let pkg_dir = packages_dir.join("neovim");
        std::fs::create_dir_all(&pkg_dir).unwrap();
        let ext = crate::commands::package::script_extension();
        std::fs::write(
            pkg_dir.join(format!("install.{ext}")),
            "#!/usr/bin/env sh\nsudo dnf install -y neovim\n",
        )
        .unwrap();

        let config = fixture_config(vec![("neovim", true)]);

        // Act
        let sut = Plan::build(
            &config,
            &["neovim".to_string()],
            Action::Install,
            &[],
            Some(&packages_dir),
        )
        .unwrap();

        // Assert
        assert!(sut.script_unmodified.is_empty());
        assert_eq!(sut.enabled, vec!["neovim"]);
    }

    #[test]
    fn test_build_ignores_missing_scripts() {
        // Arrange
        let tmp = tempfile::TempDir::new().unwrap();
        let packages_dir = tmp.path().join("packages");
        std::fs::create_dir_all(&packages_dir).unwrap();

        let config = fixture_config(vec![("neovim", true)]);

        // Act
        let sut = Plan::build(
            &config,
            &["neovim".to_string()],
            Action::Install,
            &[],
            Some(&packages_dir),
        )
        .unwrap();

        // Assert — missing scripts cannot be unmodified; package stays enabled
        assert!(sut.script_unmodified.is_empty());
        assert_eq!(sut.enabled, vec!["neovim"]);
    }

    #[test]
    fn test_build_detects_unmodified_with_script_alias() {
        // Arrange
        let tmp = tempfile::TempDir::new().unwrap();
        let packages_dir = tmp.path().join("packages");
        let pkg_dir = packages_dir.join("neovim");
        std::fs::create_dir_all(&pkg_dir).unwrap();
        let ext = crate::commands::package::script_extension();
        let script_name = format!("install.{ext}");
        // The update action is overridden to install, so it should check install.sh
        std::fs::write(
            pkg_dir.join(&script_name),
            "# Generated by homeos — fill in the install logic for neovim.\n",
        )
        .unwrap();

        let mut packages = BTreeMap::new();
        packages.insert(
            "neovim".to_string(),
            PackageConfig {
                script_aliases: BTreeMap::from([("update".to_string(), "install".to_string())]),
                enabled: true,
                ..Default::default()
            },
        );
        let config = Config {
            packages,
            ..Default::default()
        };

        // Act
        let sut = Plan::build(
            &config,
            &["neovim".to_string()],
            Action::Update,
            &["neovim".to_string()],
            Some(&packages_dir),
        )
        .unwrap();

        // Assert — the resolved script (install.sh) is reported as unmodified
        assert!(sut.enabled.is_empty());
        assert_eq!(sut.script_unmodified.get("neovim"), Some(&script_name));
    }

    #[test]
    fn test_display_shows_script_unmodified_in_skipped() {
        // Arrange
        let plan = Plan {
            action: Action::Install,
            enabled: vec!["zed".to_string()],
            disabled: vec![],
            already_installed: vec![],
            not_installed: vec![],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::from([("neovim".to_string(), "install.sh".to_string())]),
            plugins: BTreeMap::new(),
            notes: BTreeMap::new(),
        };

        // Act
        let sut = plan.display();

        // Assert
        let expected = "\
The following packages will be installed:
  zed
The following packages will be skipped:
  neovim (script unmodified: install.sh)";
        assert_eq!(sut, expected);
    }

    #[test]
    fn test_build_skips_unmodified_check_for_disabled_packages() {
        // Arrange
        let tmp = tempfile::TempDir::new().unwrap();
        let packages_dir = tmp.path().join("packages");
        let pkg_dir = packages_dir.join("neovim");
        std::fs::create_dir_all(&pkg_dir).unwrap();
        let ext = crate::commands::package::script_extension();
        std::fs::write(
            pkg_dir.join(format!("install.{ext}")),
            "# Generated by homeos — fill in the install logic for neovim.\n",
        )
        .unwrap();

        let config = fixture_config(vec![("neovim", false)]);

        // Act
        let sut = Plan::build(
            &config,
            &["neovim".to_string()],
            Action::Install,
            &[],
            Some(&packages_dir),
        )
        .unwrap();

        // Assert — disabled packages are not in enabled list, so the script check
        // does not run; the package stays in `disabled`, not `script_unmodified`.
        assert!(sut.script_unmodified.is_empty());
        assert_eq!(sut.disabled, vec!["neovim"]);
    }

    #[test]
    fn test_build_propagates_unmodified_for_update_action() {
        // Arrange — update path checks the update script too
        let tmp = tempfile::TempDir::new().unwrap();
        let packages_dir = tmp.path().join("packages");
        let pkg_dir = packages_dir.join("neovim");
        std::fs::create_dir_all(&pkg_dir).unwrap();
        let ext = crate::commands::package::script_extension();
        let script_name = format!("update.{ext}");
        std::fs::write(
            pkg_dir.join(&script_name),
            "# Generated by homeos — fill in the update logic for neovim.\n",
        )
        .unwrap();
        let config = fixture_config(vec![("neovim", true)]);
        let installed = vec!["neovim".to_string()];

        // Act
        let sut = Plan::build(
            &config,
            &["neovim".to_string()],
            Action::Update,
            &installed,
            Some(&packages_dir),
        )
        .unwrap();

        // Assert
        assert!(sut.enabled.is_empty());
        assert_eq!(sut.script_unmodified.get("neovim"), Some(&script_name));
    }

    #[test]
    fn test_build_propagates_unmodified_for_uninstall_action() {
        // Arrange — uninstall path checks the uninstall script too
        let tmp = tempfile::TempDir::new().unwrap();
        let packages_dir = tmp.path().join("packages");
        let pkg_dir = packages_dir.join("neovim");
        std::fs::create_dir_all(&pkg_dir).unwrap();
        let ext = crate::commands::package::script_extension();
        let script_name = format!("uninstall.{ext}");
        std::fs::write(
            pkg_dir.join(&script_name),
            "# Generated by homeos — fill in the uninstall logic for neovim.\n",
        )
        .unwrap();
        let config = fixture_config(vec![("neovim", true)]);
        let installed = vec!["neovim".to_string()];

        // Act
        let sut = Plan::build(
            &config,
            &["neovim".to_string()],
            Action::Uninstall,
            &installed,
            Some(&packages_dir),
        )
        .unwrap();

        // Assert
        assert!(sut.enabled.is_empty());
        assert_eq!(sut.script_unmodified.get("neovim"), Some(&script_name));
    }

    #[test]
    fn test_is_empty_when_all_script_unmodified() {
        // Arrange
        let plan = Plan {
            action: Action::Install,
            enabled: vec![],
            disabled: vec![],
            already_installed: vec![],
            not_installed: vec![],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::from([("neovim".to_string(), "install.sh".to_string())]),
            plugins: BTreeMap::new(),
            notes: BTreeMap::new(),
        };

        // Act & Assert
        assert!(plan.is_empty());
    }

    #[test]
    fn test_display_shows_script_unmodified_with_plugin() {
        // Arrange
        let plan = Plan {
            action: Action::Install,
            enabled: vec![],
            disabled: vec![],
            already_installed: vec![],
            not_installed: vec![],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::from([("neovim".to_string(), "install.sh".to_string())]),
            plugins: BTreeMap::from([("neovim".to_string(), "dnf".to_string())]),
            notes: BTreeMap::new(),
        };

        // Act
        let sut = plan.display();

        // Assert
        assert_eq!(
            sut,
            "The following packages will be skipped:\n  neovim (script unmodified: install.sh, plugin: dnf)"
        );
    }

    // --- Plugin display tests ---

    #[test]
    fn test_display_shows_plugin_name_for_enabled_package() {
        // Arrange
        let plan = Plan {
            action: Action::Install,
            enabled: vec!["neovim".to_string()],
            disabled: vec![],
            already_installed: vec![],
            not_installed: vec![],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::from([("neovim".to_string(), "dnf".to_string())]),
            notes: BTreeMap::new(),
        };

        // Act
        let sut = plan.display();

        // Assert
        assert_eq!(
            sut,
            "The following packages will be installed:\n  neovim (plugin: dnf)"
        );
    }

    #[test]
    fn test_display_shows_plugin_name_for_disabled_package() {
        // Arrange
        let plan = Plan {
            action: Action::Install,
            enabled: vec![],
            disabled: vec!["neovim".to_string()],
            already_installed: vec![],
            not_installed: vec![],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::from([("neovim".to_string(), "dnf".to_string())]),
            notes: BTreeMap::new(),
        };

        // Act
        let sut = plan.display();

        // Assert
        assert_eq!(
            sut,
            "The following packages will be skipped:\n  neovim (disabled, plugin: dnf)"
        );
    }

    #[test]
    fn test_display_shows_plugin_name_for_already_installed_package() {
        // Arrange
        let plan = Plan {
            action: Action::Install,
            enabled: vec![],
            disabled: vec![],
            already_installed: vec!["neovim".to_string()],
            not_installed: vec![],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::from([("neovim".to_string(), "dnf".to_string())]),
            notes: BTreeMap::new(),
        };

        // Act
        let sut = plan.display();

        // Assert
        assert_eq!(
            sut,
            "The following packages will be skipped:\n  neovim (already installed, plugin: dnf)"
        );
    }

    #[test]
    fn test_display_shows_plugin_name_for_not_installed_package() {
        // Arrange
        let plan = Plan {
            action: Action::Update,
            enabled: vec![],
            disabled: vec![],
            already_installed: vec![],
            not_installed: vec!["neovim".to_string()],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::from([("neovim".to_string(), "dnf".to_string())]),
            notes: BTreeMap::new(),
        };

        // Act
        let sut = plan.display();

        // Assert
        assert_eq!(
            sut,
            "The following packages will be skipped:\n  neovim (not installed, plugin: dnf)"
        );
    }

    #[test]
    fn test_display_mixed_packages_with_and_without_plugin() {
        // Arrange
        let plan = Plan {
            action: Action::Install,
            enabled: vec!["neovim".to_string(), "zed".to_string()],
            disabled: vec![],
            already_installed: vec![],
            not_installed: vec![],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::from([("neovim".to_string(), "dnf".to_string())]),
            notes: BTreeMap::new(),
        };

        // Act
        let sut = plan.display();

        // Assert
        let expected = "\
The following packages will be installed:
  neovim (plugin: dnf)
  zed";
        assert_eq!(sut, expected);
    }

    #[test]
    fn test_build_populates_plugin_for_enabled_package() {
        // Arrange
        let mut packages = BTreeMap::new();
        packages.insert(
            "neovim".to_string(),
            PackageConfig {
                plugin: Some("dnf".to_string()),
                ..Default::default()
            },
        );
        packages.insert(
            "zed".to_string(),
            PackageConfig {
                ..Default::default()
            },
        );
        let config = Config {
            packages,
            ..Default::default()
        };

        // Act
        let sut = Plan::build(
            &config,
            &["neovim".to_string(), "zed".to_string()],
            Action::Install,
            &[],
            None,
        )
        .unwrap();

        // Assert
        assert_eq!(sut.plugins.get("neovim"), Some(&"dnf".to_string()));
        assert!(!sut.plugins.contains_key("zed"));
    }

    #[test]
    fn test_build_populates_plugin_for_disabled_package() {
        // Arrange
        let mut packages = BTreeMap::new();
        packages.insert(
            "neovim".to_string(),
            PackageConfig {
                enabled: false,
                plugin: Some("dnf".to_string()),
                ..Default::default()
            },
        );
        let config = Config {
            packages,
            ..Default::default()
        };

        // Act
        let sut =
            Plan::build(&config, &["neovim".to_string()], Action::Install, &[], None).unwrap();

        // Assert
        assert_eq!(sut.plugins.get("neovim"), Some(&"dnf".to_string()));
    }

    #[test]
    fn test_display_shows_notes_for_enabled_packages() {
        // Arrange
        let plan = Plan {
            action: Action::Uninstall,
            enabled: vec!["editor".to_string(), "git".to_string()],
            disabled: vec![],
            already_installed: vec![],
            not_installed: vec![],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::new(),
            notes: BTreeMap::from([("editor".to_string(), "depends on git".to_string())]),
        };

        // Act
        let sut = plan.display();

        // Assert
        let expected = "\
The following packages will be uninstalled:
  editor (depends on git)
  git";
        assert_eq!(sut, expected);
    }

    #[test]
    fn test_display_shows_notes_with_plugin() {
        // Arrange
        let plan = Plan {
            action: Action::Uninstall,
            enabled: vec!["editor".to_string()],
            disabled: vec![],
            already_installed: vec![],
            not_installed: vec![],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::from([("editor".to_string(), "dnf".to_string())]),
            notes: BTreeMap::from([("editor".to_string(), "depends on git".to_string())]),
        };

        // Act
        let sut = plan.display();

        // Assert — notes appear first, then plugin
        let expected = "\
The following packages will be uninstalled:
  editor (depends on git, plugin: dnf)";
        assert_eq!(sut, expected);
    }

    // --- Circular dependency display tests ---

    #[test]
    fn test_display_shows_circular_dependency_in_skipped() {
        // Arrange
        let plan = Plan {
            action: Action::Install,
            enabled: vec!["zed".to_string()],
            disabled: vec![],
            already_installed: vec![],
            not_installed: vec![],
            circular_dependency: vec!["a".to_string(), "b".to_string()],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::new(),
            notes: BTreeMap::new(),
        };

        // Act
        let sut = plan.display();

        // Assert
        let expected = "\
The following packages will be installed:
  zed
The following packages will be skipped:
  a (circular dependency)
  b (circular dependency)";
        assert_eq!(sut, expected);
    }

    #[test]
    fn test_display_shows_only_circular_dependency_when_all_skipped() {
        // Arrange
        let plan = Plan {
            action: Action::Install,
            enabled: vec![],
            disabled: vec![],
            already_installed: vec![],
            not_installed: vec![],
            circular_dependency: vec!["a".to_string(), "b".to_string()],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::new(),
            notes: BTreeMap::new(),
        };

        // Act
        let sut = plan.display();

        // Assert
        let expected = "\
The following packages will be skipped:
  a (circular dependency)
  b (circular dependency)";
        assert_eq!(sut, expected);
    }

    #[test]
    fn test_display_shows_circular_dependency_with_plugin() {
        // Arrange
        let plan = Plan {
            action: Action::Install,
            enabled: vec![],
            disabled: vec![],
            already_installed: vec![],
            not_installed: vec![],
            circular_dependency: vec!["a".to_string()],
            dependency_disabled: BTreeMap::new(),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::from([("a".to_string(), "dnf".to_string())]),
            notes: BTreeMap::new(),
        };

        // Act
        let sut = plan.display();

        // Assert
        assert_eq!(
            sut,
            "The following packages will be skipped:\n  a (circular dependency, plugin: dnf)"
        );
    }

    // --- Dependency-disabled propagation tests ---

    fn fixture_config_with_deps(packages: Vec<(&str, bool, Vec<&str>)>) -> Config {
        let mut map = BTreeMap::new();
        for (name, enabled, deps) in packages {
            map.insert(
                name.to_string(),
                PackageConfig {
                    enabled,
                    depends_on: deps.into_iter().map(String::from).collect(),
                    ..Default::default()
                },
            );
        }
        Config {
            packages: map,
            ..Default::default()
        }
    }

    #[test]
    fn test_build_propagates_disabled_dep_directly() {
        // Arrange — A enabled depends on B disabled
        let config = fixture_config_with_deps(vec![("a", true, vec!["b"]), ("b", false, vec![])]);
        let packages: Vec<String> = vec!["a", "b"].into_iter().map(String::from).collect();

        // Act
        let sut = Plan::build(&config, &packages, Action::Install, &[], None).unwrap();

        // Assert — a moved out of enabled into dependency_disabled blaming b
        assert!(sut.enabled.is_empty());
        assert_eq!(sut.disabled, vec!["b"]);
        assert_eq!(sut.dependency_disabled.get("a"), Some(&"b".to_string()));
    }

    #[test]
    fn test_build_propagates_disabled_dep_transitively_blames_direct() {
        // Arrange — A → B → C, C disabled
        let config = fixture_config_with_deps(vec![
            ("a", true, vec!["b"]),
            ("b", true, vec!["c"]),
            ("c", false, vec![]),
        ]);
        let packages: Vec<String> = vec!["a", "b", "c"].into_iter().map(String::from).collect();

        // Act
        let sut = Plan::build(&config, &packages, Action::Install, &[], None).unwrap();

        // Assert — each blames its most direct unavailable dep
        assert!(sut.enabled.is_empty());
        assert_eq!(sut.disabled, vec!["c"]);
        assert_eq!(sut.dependency_disabled.get("a"), Some(&"b".to_string()));
        assert_eq!(sut.dependency_disabled.get("b"), Some(&"c".to_string()));
    }

    #[test]
    fn test_build_picks_alphabetically_first_unavailable_direct_dep() {
        // Arrange — A depends on [b, c, d]; b enabled, c disabled, d disabled
        let config = fixture_config_with_deps(vec![
            ("a", true, vec!["b", "c", "d"]),
            ("b", true, vec![]),
            ("c", false, vec![]),
            ("d", false, vec![]),
        ]);
        let packages: Vec<String> = vec!["a"].into_iter().map(String::from).collect();

        // Act
        let sut = Plan::build(&config, &packages, Action::Install, &[], None).unwrap();

        // Assert — alphabetically first of unavailable deps (c, d) is c
        assert_eq!(sut.dependency_disabled.get("a"), Some(&"c".to_string()));
    }

    #[test]
    fn test_build_does_not_propagate_for_update_action() {
        // Arrange — A enabled depends on B disabled; both in state
        let config = fixture_config_with_deps(vec![("a", true, vec!["b"]), ("b", false, vec![])]);
        let packages: Vec<String> = vec!["a", "b"].into_iter().map(String::from).collect();
        let installed = vec!["a".to_string(), "b".to_string()];

        // Act
        let sut = Plan::build(&config, &packages, Action::Update, &installed, None).unwrap();

        // Assert — update is unaffected; a runs, b skipped as disabled
        assert_eq!(sut.enabled, vec!["a"]);
        assert_eq!(sut.disabled, vec!["b"]);
        assert!(sut.dependency_disabled.is_empty());
    }

    #[test]
    fn test_build_does_not_propagate_for_uninstall_action() {
        // Arrange — A enabled depends on B disabled; both in state
        let config = fixture_config_with_deps(vec![("a", true, vec!["b"]), ("b", false, vec![])]);
        let packages: Vec<String> = vec!["a", "b"].into_iter().map(String::from).collect();
        let installed = vec!["a".to_string(), "b".to_string()];

        // Act
        let sut = Plan::build(&config, &packages, Action::Uninstall, &installed, None).unwrap();

        // Assert — uninstall ignores disabled and does not propagate
        assert_eq!(sut.enabled, vec!["a", "b"]);
        assert!(sut.dependency_disabled.is_empty());
    }

    #[test]
    fn test_build_does_not_propagate_when_no_disabled_deps() {
        // Arrange — A enabled depends on B enabled
        let config = fixture_config_with_deps(vec![("a", true, vec!["b"]), ("b", true, vec![])]);
        let packages: Vec<String> = vec!["a", "b"].into_iter().map(String::from).collect();

        // Act
        let sut = Plan::build(&config, &packages, Action::Install, &[], None).unwrap();

        // Assert
        assert_eq!(sut.enabled, vec!["a", "b"]);
        assert!(sut.dependency_disabled.is_empty());
    }

    #[test]
    fn test_build_propagates_when_disabled_dep_outside_input_list() {
        // Arrange — A enabled depends on B disabled; only A is in the input list
        let config = fixture_config_with_deps(vec![("a", true, vec!["b"]), ("b", false, vec![])]);
        let packages: Vec<String> = vec!["a"].into_iter().map(String::from).collect();

        // Act
        let sut = Plan::build(&config, &packages, Action::Install, &[], None).unwrap();

        // Assert — propagation reads from config, not just the input list
        assert!(sut.enabled.is_empty());
        assert!(sut.disabled.is_empty());
        assert_eq!(sut.dependency_disabled.get("a"), Some(&"b".to_string()));
    }

    #[test]
    fn test_build_handles_cycle_without_disabled_dep() {
        // Arrange — A ↔ B cycle, both enabled, no disabled deps
        let config = fixture_config_with_deps(vec![("a", true, vec!["b"]), ("b", true, vec!["a"])]);
        let packages: Vec<String> = vec!["a", "b"].into_iter().map(String::from).collect();

        // Act — must not loop forever
        let sut = Plan::build(&config, &packages, Action::Install, &[], None).unwrap();

        // Assert — neither classified as dependency_disabled
        assert!(sut.dependency_disabled.is_empty());
    }

    #[test]
    fn test_display_shows_dependency_disabled_in_skipped() {
        // Arrange
        let plan = Plan {
            action: Action::Install,
            enabled: vec!["zed".to_string()],
            disabled: vec!["b".to_string()],
            already_installed: vec![],
            not_installed: vec![],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::from([("a".to_string(), "b".to_string())]),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::new(),
            notes: BTreeMap::new(),
        };

        // Act
        let sut = plan.display();

        // Assert
        let expected = "\
The following packages will be installed:
  zed
The following packages will be skipped:
  b (disabled)
  a (dependency disabled: b)";
        assert_eq!(sut, expected);
    }

    #[test]
    fn test_display_shows_only_dependency_disabled_when_all_skipped() {
        // Arrange
        let plan = Plan {
            action: Action::Install,
            enabled: vec![],
            disabled: vec![],
            already_installed: vec![],
            not_installed: vec![],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::from([("a".to_string(), "b".to_string())]),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::new(),
            notes: BTreeMap::new(),
        };

        // Act
        let sut = plan.display();

        // Assert
        let expected = "\
The following packages will be skipped:
  a (dependency disabled: b)";
        assert_eq!(sut, expected);
    }

    #[test]
    fn test_display_shows_dependency_disabled_with_plugin() {
        // Arrange
        let plan = Plan {
            action: Action::Install,
            enabled: vec![],
            disabled: vec![],
            already_installed: vec![],
            not_installed: vec![],
            circular_dependency: vec![],
            dependency_disabled: BTreeMap::from([("a".to_string(), "b".to_string())]),
            script_unmodified: BTreeMap::new(),
            plugins: BTreeMap::from([("a".to_string(), "dnf".to_string())]),
            notes: BTreeMap::new(),
        };

        // Act
        let sut = plan.display();

        // Assert
        assert_eq!(
            sut,
            "The following packages will be skipped:\n  a (dependency disabled: b, plugin: dnf)"
        );
    }

    #[test]
    fn test_is_empty_when_all_dependency_disabled() {
        // Arrange — A is classified as dependency_disabled, no enabled packages
        let config = fixture_config_with_deps(vec![("a", true, vec!["b"]), ("b", false, vec![])]);
        let packages: Vec<String> = vec!["a"].into_iter().map(String::from).collect();

        // Act
        let sut = Plan::build(&config, &packages, Action::Install, &[], None).unwrap();

        // Assert
        assert!(sut.is_empty());
    }
}
